"""initial schema

Revision ID: 7812fa6667da
Revises: 
Create Date: 2026-10-03 18:44:59.594205
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.models.types


revision = '7812fa6667da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percent', sa.Integer(), nullable=False),
    sa.Column('config', app.models.types.JSONColumn(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_flags_key'), ['key'], unique=True)

    op.create_table('learning_content',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('simple_body', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.Column('reading_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('tags', app.models.types.JSONColumn(), nullable=True),
    sa.Column('offline_available', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_content', schema=None) as batch_op:
        batch_op.create_index('ix_learning_content_cat_lang', ['category', 'language'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_content_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_content_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_content_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_content_offline_available'), ['offline_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_content_order_index'), ['order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_content_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_content_slug'), ['slug'], unique=True)

    op.create_table('market_data_cache',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=48), nullable=False),
    sa.Column('series', sa.String(length=48), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('payload', app.models.types.JSONColumn(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'series', 'interval', name='uq_market_cache_key')
    )
    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_data_cache_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_cache_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_cache_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_cache_symbol'), ['symbol'], unique=False)

    op.create_table('rag_documents',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=240), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('authoritative', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('doc_metadata', app.models.types.JSONColumn(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.create_index('ix_rag_docs_cat_lang', ['category', 'language'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_authoritative'), ['authoritative'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('safety_rules',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('signal_type', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=False),
    sa.Column('explanation_hi', sa.Text(), nullable=False),
    sa.Column('explanation_ta', sa.Text(), nullable=False),
    sa.Column('verify_hint_en', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_rules_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_safety_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_rules_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_rules_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_rules_signal_type'), ['signal_type'], unique=False)

    op.create_table('system_events',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detail', app.models.types.JSONColumn(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_component'), ['component'], unique=False)
        batch_op.create_index('ix_system_events_component_created', ['component', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_level'), ['level'], unique=False)

    op.create_table('users',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('actor_user_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', app.models.types.JSONColumn(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('batch_jobs',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('summary', app.models.types.JSONColumn(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_batch_jobs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verifications_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('family_relationships',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('owner_user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('assistant_user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('relationship_label', sa.String(length=48), nullable=False),
    sa.Column('consent_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_text_version', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'assistant_user_id', name='uq_family_pair')
    )
    with op.batch_alter_table('family_relationships', schema=None) as batch_op:
        batch_op.create_index('ix_family_rel_assistant_active', ['assistant_user_id', 'active'], unique=False)
        batch_op.create_index('ix_family_rel_owner_active', ['owner_user_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_relationships_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_relationships_assistant_user_id'), ['assistant_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_relationships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_relationships_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_relationships_revoked_at'), ['revoked_at'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('reflection_session_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('pause_seconds', sa.Integer(), nullable=True),
    sa.Column('mood_note', sa.String(length=120), nullable=True),
    sa.Column('shared_with_family', sa.Boolean(), nullable=False),
    sa.Column('created_offline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_reflection_session_id'), ['reflection_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_shared_with_family'), ['shared_with_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_journal_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('learning_progress',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('content_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_learning_progress_user_content')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_learning_progress_user_done', ['user_id', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_user_id'), ['user_id'], unique=False)

    op.create_table('market_educational_scenarios',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('cache_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('concept', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('what_it_means', sa.Text(), nullable=False),
    sa.Column('how_it_is_calculated', sa.Text(), nullable=False),
    sa.Column('why_people_care', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('what_this_teaches', app.models.types.JSONColumn(), nullable=True),
    sa.Column('chart_data', app.models.types.JSONColumn(), nullable=True),
    sa.Column('chart_kind', sa.String(length=24), nullable=False),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cache_id'], ['market_data_cache.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_educational_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_educational_scenarios_cache_id'), ['cache_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_educational_scenarios_concept'), ['concept'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_educational_scenarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_educational_scenarios_is_simulation'), ['is_simulation'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_educational_scenarios_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_educational_scenarios_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_educational_scenarios_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_market_scenarios_concept_lang', ['concept', 'language'], unique=False)

    op.create_table('memories',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_memories_user_type', ['user_id', 'type'], unique=False)

    op.create_table('notifications',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('rag_chunks',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('document_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_rag_chunk_position')
    )
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_chunks_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_rag_chunks_doc_index', ['document_id', 'chunk_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_language'), ['language'], unique=False)

    op.create_table('sessions',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_sessions_user_active', ['user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('voice_enabled', sa.Boolean(), nullable=False),
    sa.Column('speech_rate', sa.Integer(), nullable=False),
    sa.Column('large_text', sa.Boolean(), nullable=False),
    sa.Column('high_contrast', sa.Boolean(), nullable=False),
    sa.Column('simple_language', sa.Boolean(), nullable=False),
    sa.Column('data_saver', sa.Boolean(), nullable=False),
    sa.Column('offline_cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('family_mode_ui', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('extra', app.models.types.JSONColumn(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_privacy_settings',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('store_analysis_history', sa.Boolean(), nullable=False),
    sa.Column('store_voice_transcripts', sa.Boolean(), nullable=False),
    sa.Column('store_uploaded_files', sa.Boolean(), nullable=False),
    sa.Column('allow_family_access', sa.Boolean(), nullable=False),
    sa.Column('analytics_opt_in', sa.Boolean(), nullable=False),
    sa.Column('on_device_preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_privacy_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_privacy_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_privacy_settings_user_id'), ['user_id'], unique=True)

    op.create_table('user_roles',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('role_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('voice_sessions',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('stt_provider', sa.String(length=32), nullable=False),
    sa.Column('tts_provider', sa.String(length=32), nullable=False),
    sa.Column('ai_provider', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('transcripts_retained', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_voice_sessions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('family_invitations',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('relationship_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('inviter_user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_scopes', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['family_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_invitations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_invitations_invitee_email'), ['invitee_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_invitations_inviter_user_id'), ['inviter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_invitations_relationship_id'), ['relationship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_invitations_token_hash'), ['token_hash'], unique=True)

    op.create_table('family_permissions',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('relationship_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['family_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_id', 'scope', name='uq_family_permission_scope')
    )
    with op.batch_alter_table('family_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_permissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_permissions_relationship_id'), ['relationship_id'], unique=False)

    op.create_table('message_analyses',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('uploaded_file_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('batch_item_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('input_kind', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('detected_language', sa.String(length=8), nullable=False),
    sa.Column('language_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('nlp_result', app.models.types.JSONColumn(), nullable=True),
    sa.Column('what_we_detected', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('what_to_verify', sa.Text(), nullable=False),
    sa.Column('what_is_uncertain', sa.Text(), nullable=False),
    sa.Column('guardrail_action', sa.String(length=16), nullable=True),
    sa.Column('guardrail_notes', app.models.types.JSONColumn(), nullable=True),
    sa.Column('ai_provider', sa.String(length=32), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analyses_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_analyses_batch_item_id'), ['batch_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_analyses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_analyses_uploaded_file_id'), ['uploaded_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('rag_embeddings',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('chunk_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', app.models.types.Embedding(), nullable=True),
    sa.Column('norm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['rag_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'model', name='uq_rag_embedding_chunk_model')
    )
    with op.batch_alter_table('rag_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_embeddings_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_embeddings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_embeddings_model'), ['model'], unique=False)

    op.create_table('voice_messages',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('session_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('audio_seconds', sa.Float(), nullable=True),
    sa.Column('guardrail_action', sa.String(length=16), nullable=True),
    sa.Column('guardrail_notes', app.models.types.JSONColumn(), nullable=True),
    sa.Column('sources', app.models.types.JSONColumn(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_voice_messages_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_messages_session_id'), ['session_id'], unique=False)

    op.create_table('analysis_signals',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('analysis_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('rule_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('signal_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('evidence_start', sa.Integer(), nullable=True),
    sa.Column('evidence_end', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('verify_hint', sa.Text(), nullable=False),
    sa.Column('detector', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['message_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['safety_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_signals_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_signals_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_signals_signal_type'), ['signal_type'], unique=False)

    op.create_table('analysis_sources',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('analysis_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('chunk_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['message_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_sources_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_sources_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_sources_created_at'), ['created_at'], unique=False)

    op.create_table('batch_items',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('job_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('uploaded_file_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('analysis_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_status', sa.String(length=48), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['message_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['batch_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_batch_items_job_status', ['job_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_items_status'), ['status'], unique=False)

    op.create_table('reflection_sessions',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('analysis_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_clarity', sa.String(length=24), nullable=True),
    sa.Column('evidence_quality', sa.String(length=24), nullable=True),
    sa.Column('time_pressure', sa.String(length=24), nullable=True),
    sa.Column('external_influence', sa.String(length=24), nullable=True),
    sa.Column('understanding', sa.String(length=24), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('signals_noticed', app.models.types.JSONColumn(), nullable=True),
    sa.Column('pause_completed', sa.Boolean(), nullable=False),
    sa.Column('pause_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['message_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reflection_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reflection_sessions_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflection_sessions_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflection_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflection_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reflection_user_completed', ['user_id', 'completed_at'], unique=False)

    op.create_table('reflection_answers',
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('session_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('question_key', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_value', sa.String(length=64), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reflection_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reflection_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reflection_answers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflection_answers_question_key'), ['question_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflection_answers_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reflection_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflection_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_reflection_answers_question_key'))
        batch_op.drop_index(batch_op.f('ix_reflection_answers_created_at'))

    op.drop_table('reflection_answers')
    with op.batch_alter_table('reflection_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_reflection_user_completed')
        batch_op.drop_index(batch_op.f('ix_reflection_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_reflection_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_reflection_sessions_completed_at'))
        batch_op.drop_index(batch_op.f('ix_reflection_sessions_analysis_id'))

    op.drop_table('reflection_sessions')
    with op.batch_alter_table('batch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_items_status'))
        batch_op.drop_index('ix_batch_items_job_status')
        batch_op.drop_index(batch_op.f('ix_batch_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_batch_items_created_at'))

    op.drop_table('batch_items')
    with op.batch_alter_table('analysis_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_sources_created_at'))
        batch_op.drop_index(batch_op.f('ix_analysis_sources_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_sources_analysis_id'))

    op.drop_table('analysis_sources')
    with op.batch_alter_table('analysis_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_analysis_signals_rule_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_signals_created_at'))
        batch_op.drop_index(batch_op.f('ix_analysis_signals_analysis_id'))

    op.drop_table('analysis_signals')
    with op.batch_alter_table('voice_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_messages_session_id'))
        batch_op.drop_index('ix_voice_messages_session_created')
        batch_op.drop_index(batch_op.f('ix_voice_messages_created_at'))

    op.drop_table('voice_messages')
    with op.batch_alter_table('rag_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_embeddings_model'))
        batch_op.drop_index(batch_op.f('ix_rag_embeddings_created_at'))
        batch_op.drop_index(batch_op.f('ix_rag_embeddings_chunk_id'))

    op.drop_table('rag_embeddings')
    with op.batch_alter_table('message_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_analyses_uploaded_file_id'))
        batch_op.drop_index(batch_op.f('ix_message_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_message_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_analyses_batch_item_id'))
        batch_op.drop_index('ix_analyses_user_created')

    op.drop_table('message_analyses')
    with op.batch_alter_table('family_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_permissions_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_family_permissions_created_at'))

    op.drop_table('family_permissions')
    with op.batch_alter_table('family_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_family_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_family_invitations_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_family_invitations_inviter_user_id'))
        batch_op.drop_index(batch_op.f('ix_family_invitations_invitee_email'))
        batch_op.drop_index(batch_op.f('ix_family_invitations_created_at'))

    op.drop_table('family_invitations')
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_sessions_user_id'))
        batch_op.drop_index('ix_voice_sessions_user_created')
        batch_op.drop_index(batch_op.f('ix_voice_sessions_created_at'))

    op.drop_table('voice_sessions')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_created_at'))

    op.drop_table('user_roles')
    with op.batch_alter_table('user_privacy_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_privacy_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_privacy_settings_created_at'))

    op.drop_table('user_privacy_settings')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_created_at'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_created_at'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index('ix_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_sessions_created_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_chunks_language'))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_document_id'))
        batch_op.drop_index('ix_rag_chunks_doc_index')
        batch_op.drop_index(batch_op.f('ix_rag_chunks_created_at'))

    op.drop_table('rag_chunks')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_resets_created_at'))

    op.drop_table('password_resets')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index('ix_memories_user_type')
        batch_op.drop_index(batch_op.f('ix_memories_user_id'))
        batch_op.drop_index(batch_op.f('ix_memories_type'))
        batch_op.drop_index(batch_op.f('ix_memories_created_at'))

    op.drop_table('memories')
    with op.batch_alter_table('market_educational_scenarios', schema=None) as batch_op:
        batch_op.drop_index('ix_market_scenarios_concept_lang')
        batch_op.drop_index(batch_op.f('ix_market_educational_scenarios_slug'))
        batch_op.drop_index(batch_op.f('ix_market_educational_scenarios_published'))
        batch_op.drop_index(batch_op.f('ix_market_educational_scenarios_language'))
        batch_op.drop_index(batch_op.f('ix_market_educational_scenarios_is_simulation'))
        batch_op.drop_index(batch_op.f('ix_market_educational_scenarios_created_at'))
        batch_op.drop_index(batch_op.f('ix_market_educational_scenarios_concept'))
        batch_op.drop_index(batch_op.f('ix_market_educational_scenarios_cache_id'))

    op.drop_table('market_educational_scenarios')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_user_id'))
        batch_op.drop_index('ix_learning_progress_user_done')
        batch_op.drop_index(batch_op.f('ix_learning_progress_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_content_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_completed_at'))

    op.drop_table('learning_progress')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_user_created')
        batch_op.drop_index(batch_op.f('ix_journal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_shared_with_family'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_reflection_session_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_created_at'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('family_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_relationships_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_family_relationships_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_family_relationships_created_at'))
        batch_op.drop_index(batch_op.f('ix_family_relationships_assistant_user_id'))
        batch_op.drop_index(batch_op.f('ix_family_relationships_active'))
        batch_op.drop_index('ix_family_rel_owner_active')
        batch_op.drop_index('ix_family_rel_assistant_active')

    op.drop_table('family_relationships')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_created_at'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_batch_jobs_user_status')
        batch_op.drop_index(batch_op.f('ix_batch_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_batch_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_batch_jobs_created_at'))

    op.drop_table('batch_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_outcome'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_level'))
        batch_op.drop_index(batch_op.f('ix_system_events_event'))
        batch_op.drop_index(batch_op.f('ix_system_events_created_at'))
        batch_op.drop_index('ix_system_events_component_created')
        batch_op.drop_index(batch_op.f('ix_system_events_component'))

    op.drop_table('system_events')
    with op.batch_alter_table('safety_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_rules_signal_type'))
        batch_op.drop_index(batch_op.f('ix_safety_rules_language'))
        batch_op.drop_index(batch_op.f('ix_safety_rules_enabled'))
        batch_op.drop_index(batch_op.f('ix_safety_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_safety_rules_code'))

    op.drop_table('safety_rules')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_documents_slug'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_published'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_language'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_checksum'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_category'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_authoritative'))
        batch_op.drop_index('ix_rag_docs_cat_lang')

    op.drop_table('rag_documents')
    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_cache_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_provider'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_created_at'))

    op.drop_table('market_data_cache')
    with op.batch_alter_table('learning_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_content_slug'))
        batch_op.drop_index(batch_op.f('ix_learning_content_published'))
        batch_op.drop_index(batch_op.f('ix_learning_content_order_index'))
        batch_op.drop_index(batch_op.f('ix_learning_content_offline_available'))
        batch_op.drop_index(batch_op.f('ix_learning_content_language'))
        batch_op.drop_index(batch_op.f('ix_learning_content_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_content_category'))
        batch_op.drop_index('ix_learning_content_cat_lang')

    op.drop_table('learning_content')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_key'))
        batch_op.drop_index(batch_op.f('ix_feature_flags_created_at'))

    op.drop_table('feature_flags')
    # ### end Alembic commands ###
